arff_base_url="https://test.openml.org"
minio_base_url="https://openml1.win.tue.nl"

[development]
allow_test_api_keys=true

[fastapi]
root_path=""

[databases.defaults]
host="openml-test-database"
port="3306"
# SQLAlchemy `dialect` and `driver`: https://docs.sqlalchemy.org/en/20/dialects/index.html
drivername="mysql"

[databases.expdb]
database="openml_expdb"

[databases.openml]
database="openml"

[routing]
minio_url="http://minio:9000/"
server_url="http://php-api:80/"

[minio]
endpoint_url="http://minio:9000"
bucket="datasets"
# Credentials should be provided via environment variables:
# OPENML_MINIO_ACCESS_KEY and OPENML_MINIO_SECRET_KEY
access_key="minioadmin"
secret_key="minioadmin"
